### PR TITLE
Fix bug #4946 BLF for 'fwd on busy'/'fwd on no answer' without destination not working

### PR DESCRIPTION
**Pull request by alexis-via**
Here is my PR to fix this bug http://projects.xivo.io/issues/4946 that I reported nearly a year ago. Successfully tested on my home Xivo 15.01.

### CODE REVIEW

**Comment by pcadottemichaud** [comment]
Thank you for your contribution. I should be able to merge your pull request for the next release (15.03).

**Comment by jpgelinas** [comment]
Does not completely work for me : blf for the function key without destination does not stay lit when I change the destination of forward.

**Comment by jpgelinas** [comment]
update : does not work in the service xlet of the xivo client but seems to work good enough from the phone.

**Comment by alexis-via** [comment]
I made more tests with my patch in this PR:
I configure a key on the user in Xivo with a forward on busy without destination.
When I update the forward busy from the Xivo client, the BLF light turns red. When I disable the forward on busy from the Xivo client, the BLF light turns green. -> OK.
When I press the BLF on the phone, here is what I get in the Xivo client: the "Simple call forwards" option becomes active, but the option "Forward on Busy" doesn't turn active -> that's a problem
When I press the BLF on the phone again, nothing happen in the Xivo client -> that's more-or-less OK. It doesn't activate "No call forward", but it's also like that when you have a key "forward on busy" with a destination.

I modified the code in xivo_cti/services/user/manager.py in the methods enable_rna_fwd() and enable_busy_fwd() to make them look like enable_unconditional_fwd(), but it doesn't change anything. In fact, the methods are called when you change options in the Xivo client, not when you press the BLF keys.
I had a look at the code in xivo_cti/services/user/notifier.py, but the code seems ok for me, because the code is similar for busy and unconditional.

I really don't see where we need to patch to fix the remaining bit.

**Comment by pcadottemichaud** [comment]
Hi, I think what you are looking for is probably in xivo_cti/services/user/manager.py
the unable_unconditional_fwd is different from the eanble_{rna,busy}_fwd in this module

**Comment by alexis-via** [comment]
@pcadottemichaud as explained in my previous message, I already tried to patch xivo_cti/services/user/manager.py in the methods enable_rna_fwd() and enable_busy_fwd() to make them look like enable_unconditional_fwd(), but, unfortunately, it doesn't solve the issue.

If you have other ideas, I'm ready to continue to try so solve this bug...

**Comment by gesanderson** [comment]
@pcadottemichaud is on vacation and won't be back for at least a month. Do you want to wait until he comes back or should I check this out ? FYI I think you might need to look at xivo-agid or xivo-confgen. When you press a BLF on the phone, the signal is sent to xivo-agid.

**Comment by alexis-via** [comment]
@gesanderson Thanks for your advice. I had a quick look at xivo_agid ; it seems that in xivo_agid/handlers/userfeatures.py, the fwd unc doesn't use the same code as fwd rna and fwd busy... so we may have to also patch this file, don't you think ?

**Comment by gesanderson** [comment]
I haven't taken the time to test and reproduce the bug, but when I reworked a bit on the func keys I remember that I had to double-check stuff in xivo-agid, xivo-ctid and xivo-confgen. So yes, there are good chances that you might need to work on xivo-agid as well.

Feel free to talk to us on IRC if you need more info. This week I'm pretty busy, but I might have a bit of time to spare next week if you need any help.

**Pull request merged**
